language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
install:
  - gem install golink
before_install:
  - gem update --system
  - gem install bundler
script:
  - script/cibuild
branches:
  only:
    - master