sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.0.0
install:
  - gem install golink
before_install:
  - gem update --system
  - gem install bundler
script:
  - script/cibuild
branches:
  only:
    - master
notifications:
  email: false