#! /usr/bin/env bash
set -e

# File config for Travis

# Directory for build project Jekyll
build_dir="./test"

# Create and enter folder test
mkdir "$build_dir"; cd "$build_dir";
printf "\nTest directory created!\n"

# Start structure Go!Link
golink -i; ls
printf "\nStructure Go! Link created!\n"

# Download dependencies
bundle install; gem install jekyll-email-protect
printf "\nDependencies installed!\n"

# Start/Build project Go!Link
bundle exec jekyll b
printf "\nGo! Link compiled with Jekyll!\n"

# Remove folder build
cd ..; rm -rf "$build_dir"

printf "\nDone! Test Go!Link competed!\n"

